version: "3.9"

services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./app
      dockerfile: Dockerfile