version: "3.9"

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/prod/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt/

  php:
    container_name: php
    build:
      context: ./app
      dockerfile: Dockerfile-prod
      args:
        - USER=${USER}
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=shoot
      - DB_PASSWORD=shoot
    volumes:
      - /etc/letsencrypt/live/cap-cap.ru/:/etc/letsencrypt/live/cap-cap.ru/